<?php

namespace Database\Seeders;

use App\Models\Refund;
use App\Models\Order;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class RefundSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $orders = Order::take(10)->get();

        foreach ($orders as $order) {
            Refund::create([
                'refund_number' => 'REF-' . strtoupper(Str::random(8)),
                'order_id' => $order->id,
                'amount' => $order->total_price > 0 ? $order->total_price : rand(100, 1000),
                'status' => collect(['pending', 'transferred', 'rejected'])->random(),
                'reason' => 'Dummy refund request for testing UI.',
                'admin_note' => 'Generated by seeder.',
            ]);
        }
    }
}
